name: Scala Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml

  release:
    needs: call-tests
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accessing full Git history & tags

      - name: Fetch main branch
        run: git fetch origin main:refs/remotes/origin/main

      - name: Check tag is from main branch
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
          MAIN_COMMIT=$(git rev-parse origin/main)

          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "::error ::Release tags must point to the latest commit on 'main'"
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Package project
        run: sbt package

      - name: Rename JAR using Git tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          JAR_PATH=$(find target/scala-* -name "progressquest_*.jar")
          cp "$JAR_PATH" "progressquest-${TAG}.jar"

      - name: Confirm renamed file
        run: ls -lh progressquest-${{ github.ref_name }}.jar

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: progressquest-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
