name: Scala CI

on:
  workflow_call:   # <-- This makes it reusable
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run tests & coverage
        run: sbt coverage test coverageReport

      - name: Check formatting
        run: sbt scalafmtCheck

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./target/scala-*/scoverage-report/scoverage.xml
          fail_ci_if_error: true
